/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manifesto' | '/produtos' | '/produto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manifesto' | '/produtos' | '/produto/$productId'
  id: '__root__' | '/' | '/manifesto' | '/produtos' | '/produto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManifestoRoute: typeof ManifestoRoute
  ProdutosRoute: typeof ProdutosRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManifestoRoute: ManifestoRoute,
  ProdutosRoute: ProdutosRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
